# Generated by Django 4.2.5 on 2023-12-08 14:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users_accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='mobile_number',
            field=models.IntegerField(default='123...'),
        ),
    ]
